version: '3'
services:
  srs:
    image: docker.bitnp.net/bitnp/live/nplive-ng-backend-legacy:master
    restart: always
    network_mode: "host"
    volumes:
      - ./deploy/srs.conf.d:/opt/srs/conf
      - ./deploy/logs:/opt/srs/objs/logs
      - ./deploy/nginx/html:/opt/srs/objs/nginx/html
